import express from "express";
import { getUserOrders,getOrderTracking,updateOrderStatus,getOrderById,getAllOrders } from "../controllers/orderController";
import { authenticateToken } from "../middlewares/authMiddleware";
import { requireAdmin } from "../middlewares/adminMiddleware";
const router=express.Router();
router.get("/admin/all",authenticateToken,requireAdmin,getAllOrders);
router.put("/:orderId/status",authenticateToken,requireAdmin,updateOrderStatus);
router.get("/",authenticateToken,getUserOrders);
router.get("/:orderId/tracking",authenticateToken,getOrderTracking);
router.get("/:id",authenticateToken,getOrderById);
export default router;
